/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tablas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class TableFrm
        extends javax.swing.JFrame
{

    /**
     * Creates new form TableFrm
     */
    public TableFrm()
    {
        initComponents();
        Lista l = new Lista();
        l.agregarNodo(15);
        l.agregarNodo(5);
        l.agregarNodo(52);
        l.agregarNodo(8);
        l.agregarNodo(75);
        l.agregarNodo(33);
        l.agregarNodo(25);
        l.agregarNodo(3);
        l.agregarNodo(74);
        l.agregarNodo(18);
        l.agregarNodo(20);

        int arregloNodos[] = new int[l.getCantNodos()];
        arregloNodos = l.imprimirLista();
        DefaultTableModel modelo = new DefaultTableModel();
        String[] cabecera =
        {
            "Nodos", "Alfa", "Beta"
        };
        modelo.setColumnIdentifiers(cabecera);
        Object[] datos = new Object[l.getCantNodos()];
        for (int i = 0; i < l.getCantNodos(); i++)
        {
            datos[0] = arregloNodos[i];
            datos[1] = "a";
            datos[2] = "b";
            modelo.addRow(datos);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbnPersonas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbnPersonas.setText("Listado de Personas");
        jbnPersonas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbnPersonasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnPersonas)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbnPersonas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnPersonasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbnPersonasActionPerformed
    {//GEN-HEADEREND:event_jbnPersonasActionPerformed
        Persona[] arrePersonas = new Persona[5];
        for (int i = 0; i < 5; i++)
        {
            arrePersonas[i] = new Persona(null,
                    null,
                    0);

        }
        arrePersonas[0] = new Persona("Carlos",
                "Ojeda",
                22);
        arrePersonas[1] = new Persona("Antonio",
                "Ramirez",
                20);
        arrePersonas[2] = new Persona("Andres",
                "Lopez",
                14);
        arrePersonas[3] = new Persona("Raul",
                "Perez",
                86);
        arrePersonas[4] = new Persona("Maria",
                "Hernandez",
                55);

        DefaultTableModel modeloPersona = new DefaultTableModel();
        String[] encabezado =
        {
            "No", "Nombre", "Apellidos", "Edad"
        };
        modeloPersona.setColumnIdentifiers(encabezado);
        Object[] datosPersona = new Object[arrePersonas.length];
        for (int i = 0; i < arrePersonas.length; i++)
        {
            datosPersona[0] = i + 1;
            datosPersona[1] = arrePersonas[i].getNombre();
            datosPersona[2] = arrePersonas[i].getApellidos();
            datosPersona[3] = arrePersonas[i].getEdad();
            modeloPersona.addRow(datosPersona);
        }
        jTable1.setModel(modeloPersona);
    }//GEN-LAST:event_jbnPersonasActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1MouseClicked
    {//GEN-HEADEREND:event_jTable1MouseClicked
        int numRenglon = jTable1.getSelectedRow();
        int numColumna = jTable1.getSelectedColumn();
        String valor = jTable1.getValueAt(numRenglon,
                numColumna).
                toString();
        JOptionPane.showMessageDialog(null,
                "Valor:" + valor + "\n" + "Renglon/Columna" + numRenglon + "," + numColumna);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TableFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbnPersonas;
    // End of variables declaration//GEN-END:variables
}
